every button , every individual button , has its own morse code . <EOS> suppose uh the uh user has pressed butto button one , then it will have a spe the circuit will generate a specific morse code to b that that button , <EOS> and the transistor will amplify the signal and send then to the l_e_d_ which translates the signal into infrared light . <EOS> like you have got a signal by pressing a button . <EOS> that's a d a morse code has been generated by the integrated circuit . <EOS> now , that signal , that morse code , has to be amplified by the transistor . <EOS> that is the use of transist transistor we which we use in the remote controller . <EOS> it will amplify the signal and it will send it to the l_e_d_ and which translates the signal into an infra infrared bits . <EOS> the sensor on the t_v_ can see the infrared light , and seeing the signal seeing the signal re it reacts appropriately , <EOS> that when it sees the amplified mo morse code signal , then it will uh it will uh know which uh what what action it has to uh do . <EOS> then it will do the appropriate action . <EOS> so uh this is how the remote controller works . <EOS>



@highlight

how it works